### ISSUE TITLE
cv2.error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:3789: error: (-215:Assertion failed) !dsize.empty() in function 'cv::hal::resize'

### ISSUE THREAD

**Issue by Cokeheart** [timojl/clipseg#49]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "D:\Blender_ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Blender_ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Blender_ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Blender_ComfyUI\ComfyUI\custom_nodes\clipseg.py", line 154, in segment_image
    heatmap_resized = resize_image(heatmap, dimensions)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Blender_ComfyUI\ComfyUI\custom_nodes\clipseg.py", line 44, in resize_image
    return cv2.resize(image, dimensions, interpolation=cv2.INTER_LINEAR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
![微信图片_20240403220839](https://github.com/timojl/clipseg/assets/124596170/9728feb0-d187-4c6c-b4a7-2b8e903aa25a)

**Comment by timojl** [comment]
This does not seem to be related to clipseg.
